language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

stages:
  - name: build
    if: tag =~ v\d+\.\d+\.\d+

jobs:
  include:
    - stage: build
      script: npm run docker:dev
    -
      script: npm run docker:prod
