version: '3.1'
services:
  postgres:
    image: postgres:9.5.8-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm

  crm:
    image: dataengi/crm:latest
    links:
      - "postgres:postgres"
    environment:
      DB_ADDRESS: postgres
    command: ["-Dpidfile.path=/dev/null"]

  crm-ui:
    image: dataengi/crm-ui:latest
    ports:
      - 80:80
    links:
      - "crm:crm"
