version: '3.1'
services:
  postgres:
    image: postgres:9.5.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - 6432:5432

  crm:
    image: dataengi/crm:latest
    links:
      - "postgres:postgres"
    environment:
      CRM_DB_HOST: postgres
      CRM_DB_PORT: 5432
    command: ["-Dpidfile.path=/dev/null"]

  crm-ui:
    image: dataengi/crm-ui:latest
    ports:
      - 80:80
    links:
      - "crm:crm"
